name: Spin down AWS Lightsail container instance on branch delete
on:
  delete
  
env:
  AWS_REGION: us-west-2 # your container region, for BattleSnake, us-west-2 is reccommended
  AWS_LIGHTSAIL_SERVICE_NAME: snekky-snek # The names of your conainer instances will start with this
  
permissions:
  contents: read
  
jobs:
  spin-down:
    name: Spin down AWS Lightsail container instance
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Delete AWS Lightsail instance on branch deletion
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          git_branch=${{ github.event.ref }}
          git_branch=${git_branch////-}
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}-${git_branch}
          echo "deleting branch: ${git_branch}"
          aws lightsail delete-container-service \
            --service-name ${service_name}
