name: Build and deploy BattleSnake Docker app to Lightsail
on:
  push

env:
  AWS_REGION: us-west-2 # your container region, for BattleSnake, us-west-2 is reccommended
  AWS_LIGHTSAIL_SERVICE_NAME: snekky-snek # matches your AWS Lightsail Service Name
  
permissions:
  contents: read

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install || true
          aws --version
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build Docker Image
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          git_branch=${git_branch////-}
          docker build -t ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}:branch-${git_branch}-commit-${git_hash} .
      - name: Push and Deploy
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          git_branch=${git_branch////-}
          service_name=${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}-${git_branch}
            
          aws lightsail push-container-image \
            --region ${{ env.AWS_REGION }} \
            --service-name ${service_name} \
            --label ${service_name} \
            --image ${{ env.AWS_LIGHTSAIL_SERVICE_NAME }}:branch-${git_branch}-commit-${git_hash}
          aws lightsail get-container-images --service-name ${service_name} | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' container.template.json > container.json
          
          deploy_url=$(aws lightsail create-container-service-deployment --service-name ${service_name} --cli-input-json file://$(pwd)/container.json | grep -Eo 'https://[^ "]+'|head -1) 
          echo "Deploy URL is: ${deploy_url}"
